import pytest

from egfr_discovery.application.dto.pipeline_documentation import (
    REQUIRED_PIPELINE_SECTION_KEYS,
    PipelineDocumentation,
    PipelineDocumentationRegistry,
    PipelineDocumentationSection,
)
from egfr_discovery.application.use_cases.render_pipeline_documentation import (
    GENERATED_NOTICE,
    RESEARCH_DISCLAIMER,
    render_pipeline_documentation,
)


def make_pipeline(pipeline_id: str = "screening") -> PipelineDocumentation:
    return PipelineDocumentation(
        pipeline_id=pipeline_id,
        title=f"{pipeline_id} title",
        summary=f"{pipeline_id} summary",
        sections=tuple(
            PipelineDocumentationSection(
                key=key, heading=f"{key} heading", body=f"{key} body"
            )
            for key in REQUIRED_PIPELINE_SECTION_KEYS
        ),
    )


def test_render_is_deterministic_and_does_not_change_registry() -> None:
    registry = PipelineDocumentationRegistry(pipelines=(make_pipeline(),))
    original = registry.model_dump()

    assert render_pipeline_documentation(registry) == render_pipeline_documentation(
        registry
    )
    assert registry.model_dump() == original


def test_render_includes_generated_notice_title_and_research_disclaimer() -> None:
    rendered = render_pipeline_documentation(
        PipelineDocumentationRegistry(pipelines=(make_pipeline(),))
    )

    assert GENERATED_NOTICE == (
        "<!-- Generated by `uv run egfr-pipeline-docs`; do not edit directly. -->"
    )
    assert rendered.startswith(f"{GENERATED_NOTICE}\n\n# Screening Pipelines\n\n")
    assert f"> {RESEARCH_DISCLAIMER}\n" in rendered
    assert "research predictions" in RESEARCH_DISCLAIMER
    assert "prioritization" in RESEARCH_DISCLAIMER
    assert "not experimentally validated medicines or clinical recommendations" in (
        RESEARCH_DISCLAIMER
    )


def test_render_preserves_declared_sections_including_extra_section() -> None:
    pipeline = make_pipeline()
    extra = PipelineDocumentationSection(
        key="limitations", heading="Limitations", body="Uncertainty remains."
    )
    sections = (pipeline.sections[0], extra, *reversed(pipeline.sections[1:]))
    pipeline = pipeline.model_copy(update={"sections": sections})

    rendered = render_pipeline_documentation(
        PipelineDocumentationRegistry(pipelines=(pipeline,))
    )

    assert f"## {pipeline.title}\n\n{pipeline.summary}\n\n" in rendered
    expected_sections = "\n\n".join(
        f"### {section.heading}\n\n{section.body}" for section in sections
    )
    assert rendered.endswith(f"{expected_sections}\n")


def test_render_preserves_registry_order() -> None:
    registry = PipelineDocumentationRegistry(
        pipelines=(make_pipeline("zeta"), make_pipeline("alpha"))
    )

    rendered = render_pipeline_documentation(registry)

    assert rendered.index("## zeta title") < rendered.index("## alpha title")


@pytest.mark.parametrize("include_pipeline", [False, True])
def test_render_has_exactly_one_trailing_newline(include_pipeline: bool) -> None:
    registry = PipelineDocumentationRegistry(
        pipelines=(make_pipeline(),) if include_pipeline else ()
    )

    rendered = render_pipeline_documentation(registry)

    assert rendered.endswith("\n")
    assert not rendered.endswith("\n\n")
