from egfr_discovery.application.dto.pipeline_documentation import (
    PipelineDocumentationRegistry,
)

GENERATED_NOTICE = (
    "<!-- Generated by `uv run egfr-pipeline-docs`; do not edit directly. -->"
)
RESEARCH_DISCLAIMER = (
    "Pipeline outputs are research predictions for prioritization, "
    "not experimentally validated medicines or clinical recommendations."
)


def render_pipeline_documentation(registry: PipelineDocumentationRegistry) -> str:
    """Render registered pipeline descriptions as deterministic Markdown."""
    blocks = [
        GENERATED_NOTICE,
        "# Screening Pipelines",
        (
            "This document describes the registered screening pipelines, their inputs, "
            "methods, and role in drug-discovery research."
        ),
        f"> {RESEARCH_DISCLAIMER}",
    ]
    for pipeline in registry.pipelines:
        blocks.extend((f"## {pipeline.title}", pipeline.summary))
        for section in pipeline.sections:
            blocks.extend((f"### {section.heading}", section.body))
    return "\n\n".join(blocks).rstrip() + "\n"
